### ISSUE TITLE
Ready for release?

### ISSUE THREAD

**Issue by jsignell** [pyviz/contrib_colormaps#5]
I think this is ready for its first release after I merge #4. @story645 do you agree?

You can see dev docs at https://pyviz-dev.github.io/contrib_colormaps

**Comment by jbednar** [comment]
Cool!  I'm happy with it!

**Comment by story645** [comment]
Totally, thanks for all your work on this!

**Comment by jsignell** [comment]
Ok I did a dev release. Now I just have one more question. I realized that I made a requirement that the user create an mpl test figure for any new colormap. Does that seem like too high a bar?

See https://github.com/pyviz/contrib_colormaps/tree/master/contrib_colormaps/tests for details

**Comment by jbednar** [comment]
Seems ok to me.

**Comment by jsignell** [comment]
Ok cool. I'll just add a note to the PR template and the top level readme

**Comment by jsignell** [comment]
Ok just conda-forge is left now. I opened a PR and will try to make sure it gets in https://github.com/conda-forge/staged-recipes/pull/10284
